### ISSUE TITLE
Using the ha_across_az template fails

### ISSUE THREAD

**Issue by klabrec** [citrix/citrix-adc-aws-cloudformation#26]
**Describe the bug**

Following the YouTube video - https://www.youtube.com/watch?v=LgGS0-Q5ODE 

How do I "Ensure that I have enough elastic IPs required for the deployment or the script will fail" ? How many do I need? I allocated 2 public EIP in my AWS console and assumed the script would associate them to the management subnet but terraform plan fails with message 

Error: Invalid index

  on citrix_adc.tf line 31, in resource "aws_instance" "citrix_adc":
  31:   ami           = var.vpx_ami_map[var.aws_region]
    |----------------
    | var.aws_region is "us-east-1"
    | var.vpx_ami_map is tuple with 2 elements

The given key does not identify an element in this collection value: a number
is required.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Which template you are using?**
 ...

**Additional context**

**Comment by sumanth-lingappa** [comment]
Hello @klabrec:

https://github.com/citrix/terraform-cloud-scripts 
is the right repository to open this issue.

Can you please move this issue to the right repository?

Closing this here.
